apiVersion: v1
kind: ReplicationController
metadata:
  name: goserver
  labels:
    name: goserver
spec:
  replicas: 7
  selector:
    name: goserver
  template:
    metadata:
      name: goserver
      labels:
        name: goserver
    spec:
      containers:
      - name: goserver
        image: devguerreiro/hello-go
